import sys
from bs4 import BeautifulSoup
import bs4

import requests
from pathlib import Path

import random

# command line arguments
appId = sys.argv[1]
scrape_str = sys.argv[2]
source = sys.argv[3]

# dl links css selectors
apkcombo_css_selector = '#best-variant-tab > div:nth-child(1) > ul > li > ul > li > a'
apksupport_css_selector = '#pageapp > div > div.downloading_tinfo > div.dinfo > div.fhelp > a'
apkpure_css_selector = '#download_link'

# Success variable for controlling which site will download the apk
success = False

# external sites direct download page
url_apkcombo = "https://apkcombo.com/" + scrape_str + "/download/apk"
url_apksupport = "https://apk.support/download-app/" +  appId
url_apkpure = "https://apkpure.com/" + scrape_str + "/" + appId + "/download"

#https://apkpure.com/efootball-2022/jp.konami.pesam/download

# # check apk exists or not on the local server
# apk = Path("/home/apkfuel/public_html/apk-downloader/user_content/apk_data/" + appId + ".apk")
# if apk.is_file():
# 	print(appId + ".apk already exists. Quitting Current Script ...")
# 	sys.exit()

# start of custom functions #

# function 00 for picking a random useragent from a file
def random_line(afile):
    line = str(next(afile))
    for num, aline in enumerate(afile, 2):
        if random.randrange(num):
            continue
        line = aline
    return line

# function 01 Beautiful soup (bs4) funciton to get details of download link of apk
def bs4_dl(site,url_sitename, css_selector):

    try:
        # getting a random user agent from a file of many useragents
        afile = open("useragents.txt")
        headers = random_line(afile).rstrip()
        print(headers)

        r  = requests.get(url_sitename, headers={'User-Agent': headers}, timeout = 5)
        data = r.text
        soup = BeautifulSoup(data,features="html.parser")
        get_dl_link = soup.select(css_selector)
        

        if(site=='apkpure.com'):
            dl_link = get_dl_link[0].get('href')
            with open("scrape_dl/" + site + "/" + appId + ".txt", "w") as fd:
                fd.write(dl_link)

        if(site=='apkcombo.com'):
            dl_link = get_dl_link[0].get('href') + "&fp=1234"
            with open("scrape_dl/" + site + "/" + appId + ".txt", "w") as fd:
                fd.write(dl_link)
        


        if(site=='apk.support'):
            dl_link = get_dl_link[0].get('href')
            with open("scrape_dl/" + site + "/" + appId + ".txt", "w") as fd:
                fd.write(dl_link)
        
        print(dl_link)

        # try:
        #     # local_link = download_file(dl_link)
        #     with open("scrape_dl/" + site + "/" + appId + ".txt", "w") as fd:
        #         fd.write(dl_link)
                
        #     success = True
            
        # except Exception as ex:
        #     success = False
        #     print(ex)

        
    except Exception as ex:
        success = False
        print("The download link is not present on the site, it means the apk does not exist, possible reason is that the apk is removed by DMCA. See below the actual Error! generated by my python code")
        print("Actual Error: ", ex)



# function 02 to download apk from external sites
# def download_file(url):
#     # local_filename = url.split('/')[-1]
#     local_filename = "user_content/apk_data/" + appId + ".apk"
#     # NOTE the stream=True parameter below
#     with requests.get(url, stream=True) as r:
#         r.raise_for_status()
#         with open(local_filename, 'wb') as f:
#             for chunk in r.iter_content(chunk_size=8192):
#                 # If you have chunk encoded response uncomment if
#                 # and set chunk_size parameter to None.
#                 #if chunk:
#                 f.write(chunk)
#     return local_filename

# Driving code -> main

print("\ntrying for another site = apk.support")
bs4_dl(site = 'apk.support',url_sitename = url_apksupport,css_selector = apksupport_css_selector)

print("\ntrying for another site = apkpure")
bs4_dl(site='apkcombo.com', url_sitename = url_apkcombo, css_selector= apkcombo_css_selector)

if(source == 'apr'):
    print("\ntrying for site = apkpure.com")
    bs4_dl(site='apkpure.com', url_sitename= url_apkpure, css_selector= apkpure_css_selector)

	
